USDC on Polygon
nimiq/nimiq-utils pull request #64
Opened 2022-12-17 17:03 UTC by onmax

Added support for USDC Polygon: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md

2022-12-17 17:04 UTC, onmax commented on src/request-link-encoding/RequestLinkEncoding.ts
> +    USDC_ON_POLYGON = 'usdc-on-polygon',
Added `ON_POLYGON` suffix to allow future integration on other blockchain if needed.

Maybe, it makes the code more verbose, but then we should put the blockchain identifier in the function parameter.

I thought this solution is cleaner.

2022-12-17 17:15 UTC, onmax commented
Before merging and publishing we have to update the version

2022-12-17 17:28 UTC, onmax commented
I am also a bit confuse. We have the same structure duplicated.
- [FiatApiSupportedCryptoCurrency on FiatApi.ts](https://github.com/nimiq/nimiq-utils/blob/31181b0e1ce65071e42485525afedef5cc5a8b60/src/fiat-api/FiatApi.ts#L2)
- [Currency on RequestLinkEncoding.ts](https://github.com/nimiq/nimiq-utils/blob/89609cb9fb4d69917342e81df7006790f9816207/src/request-link-encoding/RequestLinkEncoding.ts#L7)

Can I remove the JSON object in `RequestLinkEncoding` and update the one in `FiatApi`, to use `USDC_ON_POLYGON`?

2022-12-17 18:05 UTC, onmax commented on src/request-link-encoding/RequestLinkEncoding.ts
> +} as const;
I don't like declaring these constants here.

I would like to export them as well, so we can use in the Wallet, wdyt?

2022-12-17 18:06 UTC, onmax commented on src/request-link-encoding/RequestLinkEncoding.ts
> +} as const;
Maybe in the [`AddressBook.ts`](https://github.com/nimiq/nimiq-utils/tree/master/src/address-book/address-book.ts)?

2022-12-19 16:51 UTC, onmax commented on tests/RequestLinkEncoding.spec.ts
> +            link: `ethereum:${address}?uint256=2.014e18`,
**This is a breaking change**

The new Ethereum Create Link API uses `uint256` for the amount of the tokens to be sent as stated in [EIP-681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md)

2022-12-19 18:27 UTC, onmax commented
Once this PR is merge and new version deployed in NPM, I will merge https://github.com/nimiq/wallet/tree/usdc-request-link

2022-12-20 15:26 UTC, sisou commented on tests/RequestLinkEncoding.spec.ts
> +            link: `ethereum:${address}?uint256=2.014e18`,
type `uint256` is only to be used when interacting with a contract function (like `/transfer`). When sending ETH (or other native tokens on their chain), it still uses the `value` query parameter.

2022-12-20 15:39 UTC, sisou requested changes

2022-12-20 15:39 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +};
also `as const`?

2022-12-20 15:39 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +export const ETHEREUM_CHAINS_ID = {
```suggestion
export const ETHEREUM_CHAIN_IDS = {
```

2022-12-20 15:39 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +            // Otherwise, the address is derived from the chainId and the currency
```suggestion
            // Explicitly specify the contract address to send the transaction to.
            // Otherwise, the address is derived from the chainId and the currency.
```

2022-12-20 15:39 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +        const _decimals = currency === Currency.USDC ? decimals[Currency.USDC] : decimals[Currency.ETH];
Naming a variable with an underscore because the name is already taken is not a good idea. Find another name instead ;). You can also make the top-level `decimals` into `DECIMALS` to make clear it is a constant.

2022-12-20 15:39 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +        query.set('uint256', `${formattableNumber.toString()}e${_decimals}`);
As I commented in the other comment, `uint256` as the parameter name is only used when interacting with a contract, not for sending ETH/MATIC itself.

2022-12-20 15:39 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +    return SUPPORTED_TOKENS[ETHEREUM_CHAINS_ID.ETHEREUM_MAINNET];
I don't think this is a good idea. It will give unexpected (and therefore wrong) results for an unknown chainId, and warnings are not reliably read. Either throw here, or enforce that a contractAddress is passed if the chainId is unknown.

2022-12-20 15:39 UTC, sisou commented on tests/RequestLinkEncoding.spec.ts
> +            chainId: RequestLinkEncoding.ETHEREUM_CHAINS_ID.POLYGON_MAINNET,
I think the link should start with `polygon:` for Polygon network requests?

2022-12-20 15:41 UTC, sisou commented on tests/RequestLinkEncoding.spec.ts
> +            link: `ethereum:${mainnetUsdcContract}@137/transfer?uint256=2.014e6&address=${recipientAddress}`,
Can we get the `address` parameter to the front of the query string?

2022-12-27 12:14 UTC, onmax commented
- [X] Applied changes requested by @sisou
- [ ] Review changes
- [ ] Update to 0.8.4

2022-12-27 12:43 UTC, sisou requested changes

2022-12-27 12:43 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +    } else if (chainId && currency === Currency.USDC) {
Instead of checking for the specific USDC currency here, you could check if we have the contract for the chainId and currency combination already stored. Keep the currency dynamic, instead of hardcoding it here and in line 336. Makes it easier to add token contracts in the future only in one place instead of also in these conditions.

2022-12-27 12:43 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +        const amountName = schema === 'ethereum' ? 'value' : 'uint256';
Ethereum also supports tokens, so this also needs to be uint256 for Ethereum tokens. Better to check against if we are interacting with a contract or not.

2022-12-27 12:43 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +        const amountName = schema === 'ethereum' ? 'value' : 'uint256';
Ah, I just checked the test vectors and I see why this worked: the test vectors do not include any token transfer links on Ethereum, and don't include any native MATIC links for Polygon. If you add those this will fail.

2023-01-02 16:33 UTC, onmax commented
added new commit 
- added `isNativeToken`
- now there are tests for: ETH, token on ETH, MATIC and token on POL
-

2023-01-02 21:19 UTC, sisou requested changes

2023-01-02 21:19 UTC, sisou commented on tests/RequestLinkEncoding.spec.ts
> +                currency: RequestLinkEncoding.Currency.ETH,
The currency here needs to be removed. If not given in the test vector this can't be here. Or rather, it needs to be `vector.currency` as in the other tests. I would suggest to also add MATIC as a `currency`.

2023-01-02 21:19 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +    const nativeToken = isNativeToken(currency);
Usually we prefix booleans with `is`. So this variable should be named the same as the function. Maybe instead of this variable the function call can be used everywhere?

2023-01-02 21:19 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
>      } else if (contractAddress) {
Use the native token check instead on line 319.

2023-01-02 21:19 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +        query.set('address', recipient || getContractAddress(chainId, currency));
Why does this fall back to use the contract address for the `address` query param? That makes no sense I think.

2023-01-02 21:19 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +    return currency === Currency.ETH;
When adding MATIC, this must be adapted.

2023-01-02 21:19 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +    return tokens[currency as unknown as keyof typeof tokens] as string || '';
I'm still of the opinion this should throw instead of returning an empty string. An empty string in the URL means an invalid URL I think. @danimoh wdyt?

2023-01-12 11:58 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +    }
The `switch` statement below already has a `default` case that returns `'ethereum'`, so this condition is not needed. It would only be needed if the default case would throw an error or return something else.

2023-01-12 11:58 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +function validEthereumAddress(address: string): boolean {
Suggestion to rename to `isValidEthereumAddress` or `validateEthereumAddress`.

2023-01-12 11:58 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +        throw new Error(`Unsupported token: ${currency} on chain: ${chainId}`);
```suggestion
        throw new Error(`Unsupported token: ${currency} on chain ${chainId}`);
```

2023-01-12 11:58 UTC, sisou commented on src/request-link-encoding/RequestLinkEncoding.ts
> +        throw new Error(`Unsupported token: ${currency} on chain: ${chainId}`);
Additionally, I would suggest to add a solution to the error message. Like adding
```
You need to specify the `contractAddress` option.
```
 or similar.

2023-01-12 11:58 UTC, sisou commented on tests/RequestLinkEncoding.spec.ts
> +    it('should throw error due to bad argumnets', () => {
```suggestion
    it('should throw error due to bad arguments, () => {
```

2023-01-12 11:58 UTC, sisou commented on tests/RequestLinkEncoding.spec.ts
> +    expect(() => RequestLinkEncoding.createRequestLink('0xfb6916095ca1df60bb79Ce92ce3ea74c37c5d359', {
Did you mean to include this last `expect` in the test definition? Currently it's outside.

2023-01-12 12:00 UTC, sisou commented
CI fails because of linting errors.

2023-01-17 10:20 UTC, sisou approved these changes

2023-01-18 16:23 UTC, merged